**Question:** 
Suppose a group of 5 students take 3 exams, in English, Maths and Art.  Can you find any evidence to support the notion that students that do well in Art tend to do poorly in Maths?  The results are given below.  Do this calculation from "scratch" ie don't use inbuilt python routines for covariance.


| Student | Maths | English | Art  |
| --- | --- | --- | --- | --- |
|1	| 90	| 60	| 90 |
|2	| 90	| 90	| 30 |
|3	| 60	| 60	| 60 |
|4	| 60	| 60	| 90 |
|5	| 30	| 30	| 30 |

Let's represent the data as matrix **X**

\begin{equation}
{\bf X} = \begin{bmatrix}
90	& 60&	90\\
90&90&30 \\
60&60&60\\
60&60&90\\
30&30&30\\
\end{bmatrix}
\end{equation}

Relevant equations are:

${\bf x} = {\bf X} - {\bf 11^T}{\bf X} ( 1 / n )$

${\bf V} = {\bf x^Tx} ( 1 / n ).$

In [1]:
import numpy as np

In [28]:
X = np.matrix('90 60 90; 90 90 30; 60 60 60; 60 60 90; 30 30 30')

n = len(X)

one = np.matrix('1;1;1;1;1')

one_T = one.transpose()

x = X- one*one_T*X*(1./n)
x_T = x.transpose()

V = x_T*x*(1./n)
print(V)

[[504. 360. 180.]
 [360. 360.   0.]
 [180.   0. 720.]]


In [ ]:
Answer:
# set up the matrix A

X = np.matrix(' 90 60 90; 90 90 30; 60 60 60; 60 60 90; 30 30 30')

# make the n x 1 column vector = 1
one= np.matrix('1;1;1;1;1')
one_T = one.transpose()
n = len(X)

x = X - (one*one_T*X)*(1./n)

# show print statements
x_T = x.transpose()


V = x_T*x*(1./n)
print(V)